server:
  port: 8086
  servlet:
    context-path:

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/employee?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  output:
    ansi:
      enabled: always

logging:
  level:
    org.springframework.security: info

mybatis:
  type-aliases-package: com.bank.domain
  mapper-locations: mybatis/mapper/*.xml

# JWT
jwt:
  header: Authorization
  secret: mySecret
# token
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: /auth
      refresh: /refresh



